/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// NetworkApiRouter defines the required methods for binding the api requests to a responses for the NetworkApi
// The NetworkApiRouter implementation should parse necessary information from the http request, 
// pass the data to a NetworkApiServicer to perform the required actions, then write the service results to the http response.
type NetworkApiRouter interface { 
	ConfigGet(http.ResponseWriter, *http.Request)
	ConfigLinkIfnameDelete(http.ResponseWriter, *http.Request)
	ConfigLinkPut(http.ResponseWriter, *http.Request)
	ConfigPut(http.ResponseWriter, *http.Request)
}


// NetworkApiServicer defines the api actions for the NetworkApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type NetworkApiServicer interface { 
	ConfigGet(context.Context) (ImplResponse, error)
	ConfigLinkIfnameDelete(context.Context, string) (ImplResponse, error)
	ConfigLinkPut(context.Context, Link) (ImplResponse, error)
	ConfigPut(context.Context, Config) (ImplResponse, error)
}
