/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.2.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"

)

// NewSystemApiService creates a default api service
func NewSystemApiService() SystemApiServicer {
	return &SystemApiService{}
}

// ConfigGet - Get current live configuration 
func (s *SystemApiService) ConfigGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ConfigGet with the required logic for this service method.
	// Add api_system_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return s.ConfigGet_Impl(ctx)
}

// ConfigPatch - Patch existing configuration with new one 
func (s *SystemApiService) ConfigPatch(ctx context.Context, config Config) (ImplResponse, error) {
	// TODO - update ConfigPatch with the required logic for this service method.
	// Add api_system_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return s.ConfigPatch_Impl(ctx, config)
}

// ConfigSet - Replace existing configuration with new one 
func (s *SystemApiService) ConfigSet(ctx context.Context, config Config) (ImplResponse, error) {
	// TODO - update ConfigSet with the required logic for this service method.
	// Add api_system_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return s.ConfigSet_Impl(ctx, config)
}

// PersistConfig - Persist live configuration
func (s *SystemApiService) PersistConfig(ctx context.Context) (ImplResponse, error) {
	// TODO - update PersistConfig with the required logic for this service method.
	// Add api_system_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return s.PersistConfig_Impl(ctx)
}

// ResetConfig - Reload persisted configuration back
func (s *SystemApiService) ResetConfig(ctx context.Context) (ImplResponse, error) {
	// TODO - update ResetConfig with the required logic for this service method.
	// Add api_system_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return s.ResetConfig_Impl(ctx)
}

