/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.3.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"flag"
	"fmt"
	"runtime/debug"

	"github.com/riccardomanfrin/netconfd/logger"
	"github.com/riccardomanfrin/netconfd/nc"
)

// SystemApiService is a service that implents the logic for the SystemApiServicer
// This service should implement the business logic for every endpoint for the SystemApi API.
// Include any external packages or services that will be required by this service.
type SystemApiService struct {
	Conf Config
}

func readLiveConfig(s *SystemApiService) error {
	network, err := nc.Get()
	if err != nil {
		return err
	}
	hostNetwork := ncNetParse(network)
	s.Conf.Network = &hostNetwork
	return nil
}

// ConfigGet - Get current live configuration
func (s *SystemApiService) ConfigGet_Impl(ctx context.Context) (ImplResponse, error) {
	return GetErrorResponse(readLiveConfig(s), s.Conf)
}

// ConfigPatch - Patch existing configuration with new one
func (s *SystemApiService) ConfigPatch_Impl(ctx context.Context, config Config) (ImplResponse, error) {
	network, err := ncNetFormat(config)
	if err != nil {
		return PatchErrorResponse(err, nil)
	}
	return PatchErrorResponse(restorableConfigPatch(network), nil)
}

// ConfigSet - Replace existing configuration with new one
func (s *SystemApiService) ConfigSet_Impl(ctx context.Context, config Config) (ImplResponse, error) {
	network, err := ncNetFormat(config)
	if err != nil {
		return PatchErrorResponse(err, nil)
	}
	return PutErrorResponse(restorableConfigSet(network), nil)
}

var NoRollbackOnFailure = flag.Bool("norollbackonfailure", false, "Prevents rollback on failure (for debug purposes)")

func restorableConfigPatch(network nc.Network) error {
	existing, err := nc.Get()
	if err != nil {
		return err
	}
	//time.Sleep(1 * time.Second)
	err = nc.Patch(network)
	if err != nil {
		logger.Log.Warning("Functional/Logical error patching the config")
		if !*NoRollbackOnFailure {
			logger.Log.Info("Restoring pre-existing config")
			nc.Put(existing)
		} else {
			logger.Log.Info("Skipping pre-existing config restoration due to `--norollbackonfailure` option")
		}
		return err
	}
	return nil
}

func restorableConfigSet(network nc.Network) error {
	existing, err := nc.Get()
	if err != nil {
		return err
	}
	//time.Sleep(1 * time.Second)
	err = nc.Put(network)
	if err != nil {
		logger.Log.Warning(fmt.Sprintf("Error: %v", err.Error()))
		logger.Log.Warning("Functional/Logical error setting the config")
		debug.PrintStack()
		if !*NoRollbackOnFailure {
			logger.Log.Info("Restoring pre-existing config")
			nc.Put(existing)
		} else {
			logger.Log.Info("Skipping pre-existing config restoration due to `--norollbackonfailure` option")
		}
		return err
	}
	return nil
}

// PersistConfig - Persist live configuration
func (s *SystemApiService) PersistConfig_Impl(ctx context.Context) (ImplResponse, error) {
	err := readLiveConfig(s)
	if err != nil {
		return PostErrorResponse(err, nil)
	}
	err = s.Conf.Persist()
	return PostErrorResponse(err, nil)
}

// ResetConfig - Reload persisted configuration back
func (s *SystemApiService) ResetConfig_Impl(ctx context.Context) (ImplResponse, error) {
	err := s.Conf.LoadConfig(s.Conf.Global.CfgPath)
	if err != nil {
		return PutErrorResponse(err, nil)
	}
	network, err := ncNetFormat(s.Conf)
	if err != nil {
		return PatchErrorResponse(err, nil)
	}
	return PutErrorResponse(restorableConfigSet(network), nil)
}
