/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RouteDst - struct for RouteDst
type RouteDst struct {
	ModelDefault *ModelDefault
	string *string
}

// ModelDefaultAsRouteDst is a convenience function that returns ModelDefault wrapped in RouteDst
func ModelDefaultAsRouteDst(v *ModelDefault) RouteDst {
	return RouteDst{ ModelDefault: v}
}

// stringAsRouteDst is a convenience function that returns string wrapped in RouteDst
func stringAsRouteDst(v *string) RouteDst {
	return RouteDst{ string: v}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RouteDst) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ModelDefault
	err = json.Unmarshal(data, &dst.ModelDefault)
	if err == nil {
		jsonModelDefault, _ := json.Marshal(dst.ModelDefault)
		if string(jsonModelDefault) == "{}" { // empty struct
			dst.ModelDefault = nil
		} else {
			match++
		}
	} else {
		dst.ModelDefault = nil
	}

	// try to unmarshal data into string
	err = json.Unmarshal(data, &dst.string)
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			match++
		}
	} else {
		dst.string = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ModelDefault = nil
		dst.string = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(RouteDst)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(RouteDst)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RouteDst) MarshalJSON() ([]byte, error) {
	if src.ModelDefault != nil {
		return json.Marshal(&src.ModelDefault)
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RouteDst) GetActualInstance() (interface{}) {
	if obj.ModelDefault != nil {
		return obj.ModelDefault
	}

	if obj.string != nil {
		return obj.string
	}

	// all schemas are nil
	return nil
}

type NullableRouteDst struct {
	value *RouteDst
	isSet bool
}

func (v NullableRouteDst) Get() *RouteDst {
	return v.value
}

func (v *NullableRouteDst) Set(val *RouteDst) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteDst) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteDst) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteDst(val *RouteDst) *NullableRouteDst {
	return &NullableRouteDst{value: val, isSet: true}
}

func (v NullableRouteDst) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteDst) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


