/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ModelDefault : This is equivalent to 0.0.0.0/0 or ::/0
type ModelDefault string

// List of ModelDefault
const (
	DEFAULT ModelDefault = "default"
)

