/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Route struct {

	Dst OneOfipdefault `json:"dst,omitempty"`

	Gateway Ip `json:"gateway,omitempty"`

	// Interface name 
	Dev string `json:"dev,omitempty"`

	Protocol string `json:"protocol,omitempty"`

	Metric int32 `json:"metric,omitempty"`

	Scope Scope `json:"scope,omitempty"`

	Prefsrc Ip `json:"prefsrc,omitempty"`

	// Route flags
	Flags []string `json:"flags,omitempty"`
}


