/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Scope : scope of the object (link or global)
type Scope string

// List of Scope
const (
	LINK Scope = "link"
	GLOBAL Scope = "global"
)

