/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Link struct {

	Ifindex int32 `json:"ifindex"`

	Ifname string `json:"ifname"`

	Mtu int32 `json:"mtu,omitempty"`

	Linkinfo LinkLinkinfo `json:"linkinfo,omitempty"`

	Address string `json:"address,omitempty"`

	AddrInfo []LinkAddrInfo `json:"addr_info,omitempty"`
}


