/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"net"
)

// LinkAddrInfo struct for LinkAddrInfo
type LinkAddrInfo struct {
	// IPv4 or IPv6 address
	Local     net.IP  `json:"local"`
	Prefixlen int32   `json:"prefixlen"`
	Broadcast *string `json:"broadcast,omitempty"`
	// IPv4 or IPv6 address
	Address *net.IP `json:"address,omitempty"`
}

// NewLinkAddrInfo instantiates a new LinkAddrInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkAddrInfo(local string, prefixlen int32) *LinkAddrInfo {
	this := LinkAddrInfo{}
	this.Local.UnmarshalText([]byte(local))
	this.Prefixlen = prefixlen
	return &this
}

// NewLinkAddrInfoWithDefaults instantiates a new LinkAddrInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkAddrInfoWithDefaults() *LinkAddrInfo {
	this := LinkAddrInfo{}
	return &this
}

// GetLocal returns the Local field value
func (o *LinkAddrInfo) GetLocal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Local.String()
}

// GetLocalOk returns a tuple with the Local field value
// and a boolean to check if the value has been set.
func (o *LinkAddrInfo) GetLocalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	res := o.Local.String()
	return &res, true
}

// SetLocal sets field value
func (o *LinkAddrInfo) SetLocal(v string) {
	o.Local.UnmarshalText([]byte(v))
}

// GetPrefixlen returns the Prefixlen field value
func (o *LinkAddrInfo) GetPrefixlen() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Prefixlen
}

// GetPrefixlenOk returns a tuple with the Prefixlen field value
// and a boolean to check if the value has been set.
func (o *LinkAddrInfo) GetPrefixlenOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefixlen, true
}

// SetPrefixlen sets field value
func (o *LinkAddrInfo) SetPrefixlen(v int32) {
	o.Prefixlen = v
}

// GetBroadcast returns the Broadcast field value if set, zero value otherwise.
func (o *LinkAddrInfo) GetBroadcast() string {
	if o == nil || o.Broadcast == nil {
		var ret string
		return ret
	}
	return *o.Broadcast
}

// GetBroadcastOk returns a tuple with the Broadcast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkAddrInfo) GetBroadcastOk() (*string, bool) {
	if o == nil || o.Broadcast == nil {
		return nil, false
	}
	return o.Broadcast, true
}

// HasBroadcast returns a boolean if a field has been set.
func (o *LinkAddrInfo) HasBroadcast() bool {
	if o != nil && o.Broadcast != nil {
		return true
	}

	return false
}

// SetBroadcast gets a reference to the given string and assigns it to the Broadcast field.
func (o *LinkAddrInfo) SetBroadcast(v string) {
	o.Broadcast = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *LinkAddrInfo) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return o.Address.String()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkAddrInfo) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	res := o.Address.String()
	return &res, true
}

// HasAddress returns a boolean if a field has been set.
func (o *LinkAddrInfo) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *LinkAddrInfo) SetAddress(v string) {
	var ip net.IP
	ip.UnmarshalText([]byte(v))
	o.Address = &ip
}

func (o LinkAddrInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["local"] = o.Local
	}
	if true {
		toSerialize["prefixlen"] = o.Prefixlen
	}
	if o.Broadcast != nil {
		toSerialize["broadcast"] = o.Broadcast
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	return json.Marshal(toSerialize)
}

type NullableLinkAddrInfo struct {
	value *LinkAddrInfo
	isSet bool
}

func (v NullableLinkAddrInfo) Get() *LinkAddrInfo {
	return v.value
}

func (v *NullableLinkAddrInfo) Set(val *LinkAddrInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkAddrInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkAddrInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkAddrInfo(val *LinkAddrInfo) *NullableLinkAddrInfo {
	return &NullableLinkAddrInfo{value: val, isSet: true}
}

func (v NullableLinkAddrInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkAddrInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
