/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LinkAddrInfo struct {

	Local Ip `json:"local"`

	Prefixlen int32 `json:"prefixlen"`

	Broadcast string `json:"broadcast"`
}


