/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Namespace struct {

	// Namespace name; null or missing param identifies default (PID 1) namespace 
	Name *string `json:"name,omitempty"`

	// Series of links layer interfaces to configure within the namespace
	Links []Link `json:"links,omitempty"`

	// Namespace routes
	Routes []Route `json:"routes,omitempty"`
}


