/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ModelDefault This is equivalent to 0.0.0.0/0 or ::/0
type ModelDefault string

// List of default_
const (
	DEFAULT ModelDefault = "default"
)

func (v *ModelDefault) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ModelDefault(value)
	for _, existing := range []ModelDefault{ "default",   } {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ModelDefault", value)
}

// Ptr returns reference to default_ value
func (v ModelDefault) Ptr() *ModelDefault {
	return &v
}

type NullableModelDefault struct {
	value *ModelDefault
	isSet bool
}

func (v NullableModelDefault) Get() *ModelDefault {
	return v.value
}

func (v *NullableModelDefault) Set(val *ModelDefault) {
	v.value = val
	v.isSet = true
}

func (v NullableModelDefault) IsSet() bool {
	return v.isSet
}

func (v *NullableModelDefault) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelDefault(val *ModelDefault) *NullableModelDefault {
	return &NullableModelDefault{value: val, isSet: true}
}

func (v NullableModelDefault) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelDefault) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

