/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.2.0
 * Contact: support@athonet.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GlobalMgmt Management address
type GlobalMgmt struct {
	Host *string `json:"host,omitempty"`
	Port *int32 `json:"port,omitempty"`
}

// NewGlobalMgmt instantiates a new GlobalMgmt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGlobalMgmt() *GlobalMgmt {
	this := GlobalMgmt{}
	var host string = "127.0.0.1"
	this.Host = &host
	var port int32 = 8666
	this.Port = &port
	return &this
}

// NewGlobalMgmtWithDefaults instantiates a new GlobalMgmt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGlobalMgmtWithDefaults() *GlobalMgmt {
	this := GlobalMgmt{}
	var host string = "127.0.0.1"
	this.Host = &host
	var port int32 = 8666
	this.Port = &port
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *GlobalMgmt) GetHost() string {
	if o == nil || o.Host == nil {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalMgmt) GetHostOk() (*string, bool) {
	if o == nil || o.Host == nil {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *GlobalMgmt) HasHost() bool {
	if o != nil && o.Host != nil {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *GlobalMgmt) SetHost(v string) {
	o.Host = &v
}

// GetPort returns the Port field value if set, -1 otherwise.
func (o *GlobalMgmt) GetPort() int32 {
	if o == nil || o.Port == nil {
		var ret int32 = -1 
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalMgmt) GetPortOk() (*int32, bool) {
	if o == nil || o.Port == nil {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *GlobalMgmt) HasPort() bool {
	if o != nil && o.Port != nil {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *GlobalMgmt) SetPort(v int32) {
	o.Port = &v
}

func (o GlobalMgmt) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Host != nil {
		toSerialize["host"] = o.Host
	}
	if o.Port != nil {
		toSerialize["port"] = o.Port
	}
	return json.Marshal(toSerialize)
}

type NullableGlobalMgmt struct {
	value *GlobalMgmt
	isSet bool
}

func (v NullableGlobalMgmt) Get() *GlobalMgmt {
	return v.value
}

func (v *NullableGlobalMgmt) Set(val *GlobalMgmt) {
	v.value = val
	v.isSet = true
}

func (v NullableGlobalMgmt) IsSet() bool {
	return v.isSet
}

func (v *NullableGlobalMgmt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGlobalMgmt(val *GlobalMgmt) *NullableGlobalMgmt {
	return &NullableGlobalMgmt{value: val, isSet: true}
}

func (v NullableGlobalMgmt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGlobalMgmt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


