/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Config struct {

	Global map[string]interface{} `json:"global"`

	Links []Link `json:"links"`
}


