/*
 * netConfD API
 *
 * Network Configurator service
 *
 * API version: 0.1.0
 * Contact: support@athonet.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")
	NetworkAPIService := openapi.NewNetworkApiService()
	NetworkAPIController := openapi.NewNetworkApiController(NetworkAPIService)
	router := openapi.NewRouter(NetworkApiController)
	log.Fatal(http.ListenAndServe(":8080", router))
}
