openapi: 3.0.0
info:
  description: Network Configurator service
  version: 0.1.0
  title: netConfD API
  contact:
    email: support@athonet.com
servers:
  - url: /api/1
tags:
  - name: System
    description: Calls related to Node/Cluster management
  - name: Link
    description: Calls related to Processes/Services management
  - name: Route
    description: Calls related to Processes/Services management
paths:
  /config:
    put:
      tags:
        - System
      operationId: ConfigPut
      summary: |
        Configures and enforces a new live network configuration
      description: |
        Configures and enforces a new live network configuration
      requestBody:
        description: Full Config
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/configFull'
      responses:
        '200':
          description: Successful alignment
    get:
      tags:
        - System
      operationId: ConfigGet
      summary: |
        Configures and enforces a new live network configuration
      description: |
        Configures and enforces a new live network configuration
      responses:
        '200':
          description: Successful alignment
components:
  schemas:
    ipv4:
      type: string
      format: ipv4
    ipv6:
      type: string
      format: ipv6
    ip:
      oneOf:
        - $ref: '#/components/schemas/ipv4'
        - $ref: '#/components/schemas/ipv6'
    configFull:
      type: object
      required:
        - global
        - links
      properties:
        global:
          type: object
        links:
          type: array
          items:
            $ref: '#/components/schemas/link'
    link:
      type: object
      properties:
        ifindex:
          type: integer
        ifname:
          type: string
        #flags:
        #  type: array
        #  items:
        #    type: string
        mtu:
          type: integer
        #qdisc:
        #  type: string
        #operstate:
        #  type: string
        #group:
        #  type: string
        #txqlen:
        #  type: integer
        link_type:
          type: string
        address:
          type: string
        #broadcast:
        #  type: string
        addr_info:
          type: array
          items:
            type: object
            properties:
              #family:
              #  type: string
              local:
                $ref: '#/components/schemas/ip'
              prefixlen:
                type: integer
              broadcast:
                type: string
              #scope:
              #  type: string
              #dynamic:
              #  type: boolean
              #noprefixroute:
              #  type: boolean
              #label:
              #  type: string
              #valid_life_time:
              #  type: integer
              #preferred_life_time:
              #  type: integer
            required:
              - family
              - local
              - prefixlen
              - broadcast
              #- scope
              #- dynamic
              #- noprefixroute
              #- label
              #- valid_life_time
              #- preferred_life_time
      required:
        - ifindex
        - ifname
        #- flags
        #- mtu
        #- qdisc
        #- operstate
        #- group
        #- txqlen
        - link_type
        #- address
        #- broadcast
        #- addr_info
  
